version: '3'
networks:
  proxiedNet:
    external: true

services:
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    command:
      - "authelia"
      - "--config=/config/configuration.yml"
      - "--config=/config/configuration.acl.yml"
    environment:
      AUTHELIA_JWT_SECRET_FILE: /config/secrets/jwt_secret
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /config/secrets/storage_encryption_key
    env_file:
      - .env
    volumes:
      - ./config:/config
    networks:
      - proxiedNet
    expose:
      - 9091
    restart: unless-stopped
