networks:
  proxiedNet:
    name: proxiedNet
    driver: bridge
  database:
    external: true
  
services:
  vaultwarden:
    image: vaultwarden/server:alpine
    container_name: vaultwarden
    networks:
      - proxiedNet
      - database
    environment:
      - WEBSOCKET_ENABLED="true"
      - DATABASE_URL=postgresql://vaultwarden:${DATABASE_PASSWORD}@db/vaultwarden
    env_file:
      - .env
    volumes:
      - ./vw-data:/data
    restart: unless-stopped
