version: "2"

# https://github.com/pi-hole/docker-pi-hole/blob/master/README.md

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    domainname: pi.hole
    mac_address: d0:ca:ab:cd:ef:01
    networks:
      pihole_network:
        ipv4_address: 192.168.86.199
    dns:
      - 127.0.0.1
      - 9.9.9.9

# For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "443:443/tcp"
      - "53:53/tcp"
      - "5353/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: 'America/Chicago'
      ADMIN_EMAIL: 'cowboylaserkittenjetshark@gmail.com'
      TEMPERATUREUNIT: 'f'
      DHCP_ROUTER: '192.168.86.1'
      WEBPASSWORD: 'hhuPSN2neSN7cFWpci9ecLXUCZJxiK8scrWmEUEqASGVHn2fUNUd4TgCNZQ6ynZ7f5QY5cmYbW3wvmmgMMX63LVdMr6rQdePVYJYBxzMEkHz8b2hdxZWzqw5mgu9rX6c'
      ServerIP: '192.168.86.199'
      VIRTUAL_HOST: 'pihole.pi.hole'

# Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
      # run `touch ./var-log/pihole.log` first unless you like errors
      - './var-log/pihole.log:/var/log/pihole.log'
# Recommended but not required (DHCP needs NET_ADMIN)
#   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

networks:
  pihole_network:
    driver: macvlan
    driver_opts:
      parent: enp34s0
    ipam:
      config:
        - subnet: "192.168.86.0/24"
          gateway: "192.168.86.1"
          ip_range: "192.168.86.238/28"
