version: '3'
networks:
  proxiedNet:
    external: true

services:
  eclipse-mosquitto:
    image: eclipse-mosquitto:latest
    container_name: 'mosquitto'
    volumes:
      - './mosquitto.conf:/mosquitto/config/mosquitto.conf'
      - './data/:/mosquitto/data/'
      - './log/:/mosquitto/log/'
    networks:
      - proxiedNet
    ports:
      - '1883:1883'
      - '9001:9001'
    restart: unless-stopped
