networks:
  proxiedNet:
    name: proxiedNet
    driver: bridge
  
services:
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    networks:
      - proxiedNet
    ports:
      - 443:443
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      # - URL=<Declare in env_file>
      - VALIDATION=dns
      - SUBDOMAINS=wildcard
      - DNSPLUGIN=cloudflare
      - DOCKER_MODS=
        linuxserver/mods:swag-auto-reload|
        linuxserver/mods:swag-cloudflare-real-ip|
        linuxserver/mods:swag-dashboard
    env_file:
      - .env
    extra_hosts:
      - ${URL}:127.0.0.1
    volumes:
      - ./config:/config
    restart: unless-stopped
